FPLCup/Models/Tournament.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FPLTournament.Models
{
    public class Tournament
    {
        
     
        public int TournamentId { get; set; }
        public string name { get; set; }
        public virtual ICollection<TournamentAssignment> tournamentAssignments { get; set; }
        public virtual GroupStage groupStage { get; set; }
        public Boolean isGroupTournament { get; set; }




    }
}

FPLCup/Controllers/TournamentAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPLCup.DAL;
using FPLTournament.Models;

namespace FPLCup.Controllers
{
    public class TournamentAssignmentsController : Controller
    {
        private FPLContext db = new FPLContext();

        // GET: TournamentAssignments
        public ActionResult Index()
        {
            var tournamentAssignments = db.TournamentAssignments.Include(t => t.team).Include(t => t.tournament);
            return View(tournamentAssignments.ToList());
        }

        // GET: TournamentAssignments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentAssignment tournamentAssignment = db.TournamentAssignments.Find(id);
            if (tournamentAssignment == null)
            {
                return HttpNotFound();
            }
            return View(tournamentAssignment);
        }

        // GET: TournamentAssignments/Create
        public ActionResult Create(int? id)
        {
            ViewBag.TeamId = new SelectList(db.Teams, "TeamId", "name");

            if (id != null)
            {
                var selectList = new List<SelectListItem>();

                selectList.Add(new SelectListItem
                {
                    Value = id.ToString(),
                    Text = db.Tournaments.Find(id).name
                });

                ViewBag.TournamentId = selectList;

            }
            else
            {
                ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "name");
            }
            
            return View();
        }

       

        // POST: TournamentAssignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TournamentAssignmentId,TournamentId,TeamId")] TournamentAssignment tournamentAssignment)
        {
            if (ModelState.IsValid)
            {
                db.TournamentAssignments.Add(tournamentAssignment);
                db.SaveChanges();
                return RedirectToAction("Index", "Tournament");
            }

            ViewBag.TeamId = new SelectList(db.Teams, "TeamId", "manager", tournamentAssignment.TeamId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "name", tournamentAssignment.TournamentId);
            return View(tournamentAssignment);
        }

        // GET: TournamentAssignments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentAssignment tournamentAssignment = db.TournamentAssignments.Find(id);
            if (tournamentAssignment == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeamId = new SelectList(db.Teams, "TeamId", "manager", tournamentAssignment.TeamId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "name", tournamentAssignment.TournamentId);
            return View(tournamentAssignment);
        }

        // POST: TournamentAssignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TournamentAssignmentId,TournamentId,TeamId")] TournamentAssignment tournamentAssignment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tournamentAssignment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeamId = new SelectList(db.Teams, "TeamId", "manager", tournamentAssignment.TeamId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "name", tournamentAssignment.TournamentId);
            return View(tournamentAssignment);
        }

        // GET: TournamentAssignments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentAssignment tournamentAssignment = db.TournamentAssignments.Find(id);
            if (tournamentAssignment == null)
            {
                return HttpNotFound();
            }
            return View(tournamentAssignment);
        }

        // POST: TournamentAssignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TournamentAssignment tournamentAssignment = db.TournamentAssignments.Find(id);
            db.TournamentAssignments.Remove(tournamentAssignment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPLCup/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FPLCup.DAL;
using FPLTournament.Models;

namespace FPLCup.Controllers
{
    public class TournamentController : Controller
    {
        private FPLContext db = new FPLContext();

        // GET: Tournament
        public ActionResult Index()
        {
            var tournaments = db.Tournaments.Include(t => t.groupStage);
            return View(tournaments.ToList());
        }

        // GET: Tournament/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // GET: Tournament/Create
        public ActionResult Create()
        {
            ViewBag.TournamentId = new SelectList(db.GroupStages, "GroupStageId", "GroupStageId");
            return View();
        }

        // POST: Tournament/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //Modify so that there's separate creates if there is a Group Stage or not
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TournamentId,name,isGroupTournament")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                if (tournament.isGroupTournament == true)
                {
                    GroupStage gs = new GroupStage();
                    tournament.groupStage = gs;
                }

                db.Tournaments.Add(tournament);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TournamentId = new SelectList(db.GroupStages, "GroupStageId", "GroupStageId", tournament.TournamentId);
            return View(tournament);
        }

        // GET: Tournament/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            ViewBag.TournamentId = new SelectList(db.GroupStages, "GroupStageId", "GroupStageId", tournament.TournamentId);
            return View(tournament);
        }

        // POST: Tournament/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TournamentId,name,isGroupTournament")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tournament).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TournamentId = new SelectList(db.GroupStages, "GroupStageId", "GroupStageId", tournament.TournamentId);
            return View(tournament);
        }

        // GET: Tournament/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // POST: Tournament/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tournament tournament = db.Tournaments.Find(id);
            db.Tournaments.Remove(tournament);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FPLCup/Views/Tournament/Create.cshtml
@model FPLTournament.Models.Tournament

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isGroupTournament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isGroupTournament)
                    @Html.ValidationMessageFor(model => model.isGroupTournament, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FPLCup/Views/Tournament/Delete.cshtml
@model FPLTournament.Models.Tournament

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.groupStage.GroupStageId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupStage.GroupStageId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isGroupTournament)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isGroupTournament)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FPLCup/Views/Tournament/Details.cshtml
@model FPLTournament.Models.Tournament

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.groupStage.GroupStageId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupStage.GroupStageId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isGroupTournament)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isGroupTournament)
        </dd>

    </dl>
    <h4>Teams</h4>
    <table class="table">
        <tr>
            <th>
                Team
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.tournamentAssignments)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.team.name)
                </td>
            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TournamentId }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Add team", "Create", "TournamentAssignments", new { id = Model.TournamentId },null)
</p>

FPLCup/Views/Tournament/Edit.cshtml
@model FPLTournament.Models.Tournament

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentId)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isGroupTournament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isGroupTournament)
                    @Html.ValidationMessageFor(model => model.isGroupTournament, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FPLCup/Views/Tournament/Index.cshtml
@model IEnumerable<FPLTournament.Models.Tournament>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isGroupTournament)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isGroupTournament)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TournamentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TournamentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TournamentId })
        </td>
    </tr>
}

</table>